package com.example.assignment1

import android.annotation.SuppressLint
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    @SuppressLint("SetTextI18n", "WrongViewCast")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        //Declaring the View
        val ageNumber = findViewById<EditText>(R.id.ageNumber)
        val btnGenerate = findViewById<Button>(R.id.btnGenerate)
        val btnCancel = findViewById<Button>(R.id.btnClear)
        val txtResult = findViewById<TextView>(R.id.txtResult)

        btnGenerate.setOnClickListener {
            val age = ageNumber.text.toString().toIntOrNull()
            if (age != null) {
                val result = when (age) {
                    in 20..29 -> "Amy Winehouse"// singer
                    in 30..39 -> "Wolfgang Amadeus Mozart"//classical music composer
                    in 40..49 -> "Pablo Escobar"// infamous drug lord
                    in 55..59 -> "Steve Jobs"// Apple founder
                    in 60..69 -> "Karl Marx"// Philosopher
                    in 70..79 -> "Stephen Hawking"// Scientist
                    in 80..85 -> "Neil Armstrong"// Astronaut
                    in 86..89 -> "Mother Theresa"//Humanitarian
                    in 90..95 -> "Fidel Castro"// Cuban communist and dictator
                    in 96..100 -> "Queen Elizabeth II"// 21st Century British Monarch

                    else -> " null"
                }
                txtResult.text = "age:$age\n${
                    when (result) {
                        "Amy Winehouse" -> " Amy Winehouse died at the age of 27 after struggles with substance abuse."
                        "Wolfgang Amadeus Mozart" -> "Wolfgang Amadeus Mozart died at the age of 35,he was a classical music composer."
                        "Pablo Escobar" -> " Pablo Escobar died at the age of 44, he is dubbed the 'King of cocaine'  ."
                        "Steve Jobs" -> " Steve Jobs died at the age of 56, he founded Apple inc "
                        "Karl Marx" -> "Karl Marx died at the age of 64, he was a critic of capitalism"
                        "Stephen Hawking" -> "Stephen Hawking died at the age of 76, he was a brilliant theoretical physicist."
                        "Neil Armstrong" -> " Neil Armstrong died at the age of 82, he was the first man to step on the moon."
                        "Mother Theresa" -> " Mother Theresa died at the age of 87, she was dedicated to the poor, sick and dying."
                        "Fidel Castro" -> "Fidel Castro died at the age of 90, he was a cuban communist"
                        "Queen Elizabeth II" -> "Queen Elizabeth II died at the age of 96, she was the longest serving british monarch."

                        else -> "oops! age is out of range."
                    }
                }"

            } else {
                txtResult.text = "enter age in specified field"
            }
        }
        btnCancel.setOnClickListener {
            ageNumber.text.clear()
            txtResult.text = ""
        }

    }
}
